POST http://localhost:8080/api/articles
Content-Type: application/json

{
  "title" : "제목입니당.",
  "content" : "내용입니당."
}


###
GET http://localhost:8080/api/articles


###
GET http://localhost:8080/api/articles/1


###
DELETE http://localhost:8080/api/articles/1


###
PUT http://localhost:8080/api/articles/1
Content-Type: application/json

{
  "title" : "집게리아인가요?",
  "content" : "아뇨 뚱인데요."
}